### ISSUE TITLE
error while executing scripts/test.py

### ISSUE THREAD

**Issue by ayushgoyaal** [luckiezhou/DynamicTriad#12]
I am getting the following error while running test.py. I have installed all the dependencies. 

here is the log:
Checking mygraph submodule ...
Traceback (most recent call last):
  File "scripts/test.py", line 13, in <module>
    raise RuntimeError("mygraph submodule not avaiable: {}".format(str(e)))
RuntimeError: mygraph submodule not avaiable: /home/raavan/mountedDrives/dynamicGraphs/DynamicTriad-master/core/mygraph.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

**Comment by luckiezhou** [comment]
After some googling, I've found a related stackoverflow question [here](https://stackoverflow.com/questions/5810101/undefined-boost-python-symbol-boostpythondetailinit-module).
It seems to be an incompatibility problem between python versions, that the function boost::python::detail::init_module is defined differently in python 2 and 3.
As for your specific problem, your loader is looking for a python 3 function, which is unusual as the build script requires a python 2.7 environment.
I'm not sure about the exact reason, but my guess is that you are somehow building the module with python 3 headers in combination with python 2 libraries.
Please check if this is the case. (p.s. the key to debugging this problem is to trace the value of the macro  PY_VERSION_HEX during compilation).
