### ISSUE TITLE
How to set the paths before running "bash build.sh"

### ISSUE THREAD

**Issue by lowkeygit** [luckiezhou/DynamicTriad#5]
How to set the paths before running "bash build.sh"? Would you give me more specific instructions? 

> PYTHON_LIBRARY? (default: /usr/lib64/libpython2.7.so.1.0, use a space ' ' to leave it empty) 
> PYTHON_INCLUDE_DIR? (default: /usr/include/python2.7, use a space ' ' to leave it empty) 
> EIGEN3_INCLUDE_DIR? (default: /usr/include, use a space ' ' to leave it empty) 
> BOOST_ROOT? (default: , use a space ' ' to leave it empty) ~/boost_1_54_1

Many Thanks,

**Comment by luckiezhou** [comment]
@lowkeygit 
I think you may leave the first two envs to their default values, because they are expected to be automatically detected in most cases and your paths in the comment seems reasonable.

As for the EIGEN3_INCLUDE_DIR, after you have installed the eigen3 library, you are expected to find a directory named Eigen containing eigen3 headers. Set the env to its parent directory. For example, if you've got /usr/include/Eigen, then simply keep the default value (/usr/include).

BOOST_ROOT is another commonly used environment variable, where boost libs and headers are found inside the corresponding directory (do some googling and you'll get more information about this). An example is that: download the boost source package, extract to get a directory, call boost build script, and the path to the directory you've got is the proper value for BOOST_ROOT.
However, this is far from an excellent solution to detect boost library, because the structure of installed boost library varies between platforms. I'll try to modify the build script if proper information about your installation is provided.

**Comment by lowkeygit** [comment]
Thank you. The configuration is good now.
